"""Materialize reviewer-facing tables for the V3 external-validity plan.

The script only summarizes completed, machine-readable artifacts.  It does
not recompute estimates, silently drop blocked analyses, or turn engineering
probes into scientific evidence.  It is intentionally small so that the
tables used by the manuscript remain directly traceable to the ledgers.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper/iclr2027"
MANIFEST = ROOT / "artifacts/manifests"


def _fmt(value: object, digits: int = 3) -> str:
    if value is None or pd.isna(value):
        return "--"
    return f"{float(value):.{digits}f}"


def _write(path: Path, text: str) -> None:
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def comparator_table() -> dict[str, object]:
    source = MANIFEST / "strong_comparator_v3/strong_comparator_v3_summary.csv"
    frame = pd.read_csv(source)
    null = frame.loc[frame["inversion_fraction"] == 0]
    alternative = frame.loc[frame["inversion_fraction"] > 0]
    order = [
        "d_adj", "kendall", "kendall_bootstrap", "kendall_matched_null",
        "spearman", "top10_jaccard", "jaccard_bootstrap",
        "jaccard_matched_null", "stable_inversion",
    ]
    labels = {
        "d_adj": "$D_{\\rm adj}$ (legacy percentile interval; invalid)",
        "kendall": "Kendall",
        "kendall_bootstrap": "Kendall + label bootstrap",
        "kendall_matched_null": "Kendall + matched null",
        "spearman": "Spearman",
        "top10_jaccard": "Top-10 Jaccard",
        "jaccard_bootstrap": "Jaccard + label bootstrap",
        "jaccard_matched_null": "Jaccard + matched null",
        "stable_inversion": "Stable inversion",
    }
    rows: list[str] = []
    for method in order:
        one_null = null.loc[null["method"] == method]
        one_alt = alternative.loc[alternative["method"] == method]
        if one_null.empty:
            continue
        rows.append(
            f"{labels[method]} & {_fmt(one_null.false_transport_rate.mean())} & "
            f"{_fmt(one_null.coverage_90.mean())} & "
            f"{_fmt(one_alt.power.mean())} & {_fmt(one_alt.coverage_90.mean())} & "
            f"{_fmt(one_null.mae.mean())} \\\\" 
        )
    tex = r"""\begin{table}[t]
\centering
\small
\setlength{\tabcolsep}{3.5pt}
\caption{Strong comparator calibration in the registered 120-condition benchmark. Null false-transport and 90\% coverage average over all zero-inversion conditions; alternative power and coverage average over the 0.1 and 0.4 inversion surfaces. MAE is to each method's own declared population target and is therefore not a universal ranking of estimators.}
\label{tab:v3-comparator}
\begin{tabular}{lrrrrr}
\toprule
Method & Null FTR & Null cov. & Alt. power & Alt. cov. & Null MAE \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}"""
    target = OUT / "supplement_v3_comparator_table.tex"
    _write(target, tex)
    return {
        "source": source.relative_to(ROOT).as_posix(),
        "conditions": int(frame[["law", "depth", "resolution", "noise_scale", "inversion_fraction"]].drop_duplicates().shape[0]),
        "rows": int(len(rows)),
        "output": target.relative_to(ROOT).as_posix(),
        "null_false_transport_rate": {
            str(k): float(v)
            for k, v in null.groupby("method")["false_transport_rate"].mean().to_dict().items()
        },
    }


def comparator_claim_macros() -> dict[str, float]:
    source = MANIFEST / "strong_comparator_v3/strong_comparator_v3_summary.csv"
    frame = pd.read_csv(source)
    null = frame.loc[frame["inversion_fraction"] == 0]
    alt = frame.loc[frame["inversion_fraction"] > 0]
    values = {
        "PTLNullDAdjFTR": null.loc[null.method == "d_adj", "false_transport_rate"].mean(),
        "PTLNullKendallFTR": null.loc[null.method == "kendall", "false_transport_rate"].mean(),
        "PTLNullSpearmanFTR": null.loc[null.method == "spearman", "false_transport_rate"].mean(),
        "PTLNullKendallMatchedFTR": null.loc[null.method == "kendall_matched_null", "false_transport_rate"].mean(),
        "PTLNullJaccardFTR": null.loc[null.method == "top10_jaccard", "false_transport_rate"].mean(),
        "PTLNullJaccardMatchedFTR": null.loc[null.method == "jaccard_matched_null", "false_transport_rate"].mean(),
        "PTLAltDAdjPower": alt.loc[alt.method == "d_adj", "power"].mean(),
        "PTLAltKendallMatchedPower": alt.loc[alt.method == "kendall_matched_null", "power"].mean(),
        "PTLAltJaccardMatchedPower": alt.loc[alt.method == "jaccard_matched_null", "power"].mean(),
    }
    lines = [
        "% Generated by scripts/write_v3_manuscript_tables.py; do not edit by hand.",
    ]
    for key, value in values.items():
        lines.append(f"\\newcommand{{\\{key}}}{{{float(value):.3f}}}")
    target = OUT / "generated_v3_claims.tex"
    _write(target, "\n".join(lines))
    values["output"] = target.relative_to(ROOT).as_posix()  # type: ignore[assignment]
    return values


def feng_table() -> dict[str, object]:
    source = MANIFEST / "external/feng_hipsci/feng_biological_replication_summary.csv"
    frame = pd.read_csv(source)
    labels = {
        "same_donor_different_line": "Same donor, different line",
        "different_donor": "Different donor",
    }
    rows = []
    for _, row in frame.iterrows():
        rows.append(
            f"{labels.get(row.pair_type, row.pair_type)} & {int(row.n_line_pairs)} & "
            f"{int(row.n_targets_median)} & {_fmt(row.kendall_distance_median)} & "
            f"{_fmt(row.spearman_distance_median)} & {_fmt(row.top10_jaccard_distance_median)} \\\\" 
        )
    tex = r"""\begin{table}[t]
\centering
\small
\setlength{\tabcolsep}{3.5pt}
\caption{Outcome-blind Feng multi-donor iPSC audit. Risks are RMS response magnitudes over the frozen 1,000-gene panel, so this is a biological-replication audit rather than a full raw-cell $D_{\rm adj}$ hierarchy. The same-donor and different-donor rank distances are similar; no cross-donor excess is promoted.}
\label{tab:v3-feng}
\begin{tabular}{lrrrrr}
\toprule
Comparison & Pairs & Targets & Kendall $d$ & Spearman $d$ & Top-10 Jaccard $d$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}"""
    target = OUT / "supplement_v3_feng_table.tex"
    _write(target, tex)
    return {
        "source": source.relative_to(ROOT).as_posix(),
        "rows": int(len(rows)),
        "output": target.relative_to(ROOT).as_posix(),
        "status": "neutral_no_cross_donor_excess_promoted",
    }


def adaptive_table() -> dict[str, object] | None:
    source = MANIFEST / "adaptive_measurement_v1/adaptive_measurement_allocation_v1_summary.csv"
    if not source.is_file():
        return None
    frame = pd.read_csv(source)
    policy_col = "policy" if "policy" in frame.columns else "allocation_policy"
    rows = []
    for policy, group in frame.groupby(policy_col, sort=False):
        rows.append(
            f"{str(policy).replace('_', ' ')} & {_fmt(group.median_absolute_error.mean())} & "
            f"{_fmt(group.median_ci_width.mean())} & {_fmt(group.detection_rate.mean())} & "
            f"{_fmt(group.resolution_rate.mean())} & {_fmt(group.error_reduction_vs_uniform.mean())} \\\\" 
        )
    tex = r"""\begin{table}[t]
\centering
\small
\setlength{\tabcolsep}{3.5pt}
\caption{Transport-aware measurement allocation on the held-out Frangieh risk surface. Values average across the registered transfer--metric surfaces; the adaptive policy is promoted to the main text only if its error reduction and resolution gains are consistent rather than driven by one surface.}
\label{tab:v3-adaptive}
\begin{tabular}{lrrrrr}
\toprule
Policy & Abs. error & CI width & Detection & Resolution & Error reduction \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}"""
    target = OUT / "supplement_v3_adaptive_table.tex"
    _write(target, tex)
    return {
        "source": source.relative_to(ROOT).as_posix(),
        "rows": int(len(rows)),
        "output": target.relative_to(ROOT).as_posix(),
    }


def realdata_semisynthetic_table() -> dict[str, object] | None:
    source = MANIFEST / "realdata_semisynthetic_v1/frangieh_realdata_semisynthetic_summary.csv"
    if not source.is_file():
        return None
    frame = pd.read_csv(source)
    methods = [
        "d_adj", "kendall", "kendall_matched_null", "spearman",
        "top10_jaccard", "jaccard_matched_null", "stable_inversion",
    ]
    labels = {
        "d_adj": "$D_{\\rm adj}$ (U-corrected)",
        "kendall": "Kendall",
        "kendall_matched_null": "Kendall + matched null",
        "spearman": "Spearman",
        "top10_jaccard": "Top-10 Jaccard",
        "jaccard_matched_null": "Jaccard + matched null",
        "stable_inversion": "Stable inversion",
    }
    rows = []
    for method in methods:
        null = frame.loc[(frame["mode"] == "same_context_null") & frame["method"].eq(method)]
        alt = frame.loc[(frame["mode"] == "controlled_alternative") & frame["method"].eq(method)]
        powers = []
        for fraction in (0.05, 0.10, 0.20, 0.40):
            powers.append(_fmt(alt.loc[alt.injection_fraction.eq(fraction), "power"].mean()))
        rows.append(
            f"{labels[method]} & {_fmt(null.false_transport_rate.mean())} & "
            f"{_fmt(null.coverage_90.mean())} & " + " & ".join(powers) + " \\\\" 
        )
    tex = r"""\begin{table}[t]
\centering
\small
\setlength{\tabcolsep}{3pt}
\caption{Legacy real-data semi-synthetic comparator audit derived from the
Frangieh raw-cell lineage. The same-context null resamples the Control-context
canonical risk replicates; alternatives cyclically permute 5--40\% of the
60-label panel (the levels denote labels permuted, not realized pair
inversions). Values average over five cell budgets. The $D_{\rm adj}$ interval
is the failed hierarchical percentile procedure and is not used for any
detectability conclusion; final seed-block inference is reported separately in
Table~\ref{tab:dadj-calibration}.}
\label{tab:v3-realdata-semisynthetic}
\begin{tabular}{lrrrrrr}
\toprule
Method & Null FTR & Null cov. & 5\% power & 10\% power & 20\% power & 40\% power \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}"""
    target = OUT / "supplement_v3_realdata_semisynthetic_table.tex"
    _write(target, tex)
    return {
        "source": source.relative_to(ROOT).as_posix(),
        "rows": int(len(rows)),
        "output": target.relative_to(ROOT).as_posix(),
        "status": "executed_supplementary_calibration",
    }


def main() -> int:
    result = {
        "schema_version": 1,
        "comparator": comparator_table(),
        "comparator_claim_macros": comparator_claim_macros(),
        "feng": feng_table(),
        "adaptive": adaptive_table(),
        "realdata_semisynthetic": realdata_semisynthetic_table(),
    }
    target = MANIFEST / "v3_manuscript_integration.json"
    target.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
